### ISSUE TITLE
Can't Install scopen

### ISSUE THREAD

**Issue by MayaTalukdar** [CostaLab/scopen#15]
I am trying to install scopen with the given instructions, but am having trouble successfully installing it. 

I am installing scopen in a fresh conda environment created with the command: 

mamba create -n scOPEN_new_env python=3.8 anaconda 

I then run the command pip install scopen. 

However, I am getting this output:
ollecting scopen
  Downloading scOpen-0.1.7.tar.gz (117 kB)
     |████████████████████████████████| 117 kB 2.1 MB/s            
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in ./.conda/envs/scOPEN_new_env/lib/python3.8/site-packages (from scopen) (1.20.3)
Requirement already satisfied: h5py in ./.conda/envs/scOPEN_new_env/lib/python3.8/site-packages (from scopen) (3.3.0)
Requirement already satisfied: six in ./.conda/envs/scOPEN_new_env/lib/python3.8/site-packages (from scopen) (1.16.0)
Requirement already satisfied: pandas in ./.conda/envs/scOPEN_new_env/lib/python3.8/site-packages (from scopen) (1.3.3)
Requirement already satisfied: scipy in ./.conda/envs/scOPEN_new_env/lib/python3.8/site-packages (from scopen) (1.5.3)
Requirement already satisfied: tables in ./.conda/envs/scOPEN_new_env/lib/python3.8/site-packages (from scopen) (3.6.1)
Requirement already satisfied: matplotlib in ./.conda/envs/scOPEN_new_env/lib/python3.8/site-packages (from scopen) (3.4.3)
Requirement already satisfied: scikit-learn in ./.conda/envs/scOPEN_new_env/lib/python3.8/site-packages (from scopen) (1.0)
Requirement already satisfied: kneed in ./.conda/envs/scOPEN_new_env/lib/python3.8/site-packages (from scopen) (0.7.0)
Requirement already satisfied: pillow>=6.2.0 in ./.conda/envs/scOPEN_new_env/lib/python3.8/site-packages (from matplotlib->scopen) (8.3.2)
Requirement already satisfied: pyparsing>=2.2.1 in ./.conda/envs/scOPEN_new_env/lib/python3.8/site-packages (from matplotlib->scopen) (2.4.7)
Requirement already satisfied: python-dateutil>=2.7 in ./.conda/envs/scOPEN_new_env/lib/python3.8/site-packages (from matplotlib->scopen) (2.8.2)
Requirement already satisfied: cycler>=0.10 in ./.conda/envs/scOPEN_new_env/lib/python3.8/site-packages (from matplotlib->scopen) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in ./.conda/envs/scOPEN_new_env/lib/python3.8/site-packages (from matplotlib->scopen) (1.3.2)
Requirement already satisfied: pytz>=2017.3 in ./.conda/envs/scOPEN_new_env/lib/python3.8/site-packages (from pandas->scopen) (2021.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in ./.conda/envs/scOPEN_new_env/lib/python3.8/site-packages (from scikit-learn->scopen) (3.0.0)
Requirement already satisfied: joblib>=0.11 in ./.conda/envs/scOPEN_new_env/lib/python3.8/site-packages (from scikit-learn->scopen) (1.1.0)
Requirement already satisfied: numexpr>=2.6.2 in ./.conda/envs/scOPEN_new_env/lib/python3.8/site-packages (from tables->scopen) (2.7.3)
Building wheels for collected packages: scopen
  Building wheel for scopen (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /PHShome/mt1036/.conda/envs/scOPEN_new_env/bin/python3.8 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-g9cehiwo/scopen_f0e95588906e44808732495d2f7d01cd/setup.py'"'"'; __file__='"'"'/tmp/pip-install-g9cehiwo/scopen_f0e95588906e44808732495d2f7d01cd/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-laj4v41z
       cwd: /tmp/pip-install-g9cehiwo/scopen_f0e95588906e44808732495d2f7d01cd/
  Complete output (14 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/scopen
  copying scopen/MF.py -> build/lib.linux-x86_64-3.8/scopen
  copying scopen/Main.py -> build/lib.linux-x86_64-3.8/scopen
  copying scopen/Utils.py -> build/lib.linux-x86_64-3.8/scopen
  copying scopen/__init__.py -> build/lib.linux-x86_64-3.8/scopen
  copying scopen/__version__.py -> build/lib.linux-x86_64-3.8/scopen
  running build_ext
  cythoning ./scopen/cdnmf_fast.pyx to ./scopen/cdnmf_fast.c
  error: /tmp/pip-install-g9cehiwo/scopen_f0e95588906e44808732495d2f7d01cd/scopen/cdnmf_fast.pyx
  ----------------------------------------
  ERROR: Failed building wheel for scopen
  Running setup.py clean for scopen
Failed to build scopen
Installing collected packages: scopen
    Running setup.py install for scopen ... error
    ERROR: Command errored out with exit status 1:
     command: /PHShome/mt1036/.conda/envs/scOPEN_new_env/bin/python3.8 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-g9cehiwo/scopen_f0e95588906e44808732495d2f7d01cd/setup.py'"'"'; __file__='"'"'/tmp/pip-install-g9cehiwo/scopen_f0e95588906e44808732495d2f7d01cd/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-j427poti/install-record.txt --single-version-externally-managed --compile --install-headers /PHShome/mt1036/.conda/envs/scOPEN_new_env/include/python3.8/scopen
         cwd: /tmp/pip-install-g9cehiwo/scopen_f0e95588906e44808732495d2f7d01cd/
    Complete output (14 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/scopen
    copying scopen/MF.py -> build/lib.linux-x86_64-3.8/scopen
    copying scopen/Main.py -> build/lib.linux-x86_64-3.8/scopen
    copying scopen/Utils.py -> build/lib.linux-x86_64-3.8/scopen
    copying scopen/__init__.py -> build/lib.linux-x86_64-3.8/scopen
    copying scopen/__version__.py -> build/lib.linux-x86_64-3.8/scopen
    running build_ext
    cythoning ./scopen/cdnmf_fast.pyx to ./scopen/cdnmf_fast.c
    error: /tmp/pip-install-g9cehiwo/scopen_f0e95588906e44808732495d2f7d01cd/scopen/cdnmf_fast.pyx
    ----------------------------------------
ERROR: Command errored out with exit status 1: /PHShome/mt1036/.conda/envs/scOPEN_new_env/bin/python3.8 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-g9cehiwo/scopen_f0e95588906e44808732495d2f7d01cd/setup.py'"'"'; __file__='"'"'/tmp/pip-install-g9cehiwo/scopen_f0e95588906e44808732495d2f7d01cd/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-j427poti/install-record.txt --single-version-externally-managed --compile --install-headers /PHShome/mt1036/.conda/envs/scOPEN_new_env/include/python3.8/scopen Check the logs for full command output.

Any input would be appreciated!

**Comment by lzj1769** [comment]
Hi @MayaTalukdar 

I just released a new version of scopen (v1.0.1), can you try again?
simply by running the following command:
`pip install scopen`

best,
Li

**Comment by MayaTalukdar** [comment]
Hi Li, 

Thank you very much for your fast reply! Unfortunately, I am still getting a similar error: 
Collecting scopen
  Downloading scOpen-1.0.1.tar.gz (126 kB)
     |████████████████████████████████| 126 kB 2.2 MB/s            
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in ./.conda/envs/scopen_env/lib/python3.7/site-packages (from scopen) (1.20.3)
Requirement already satisfied: h5py in ./.conda/envs/scopen_env/lib/python3.7/site-packages (from scopen) (3.4.0)
Requirement already satisfied: six in ./.conda/envs/scopen_env/lib/python3.7/site-packages (from scopen) (1.16.0)
Requirement already satisfied: pandas in ./.conda/envs/scopen_env/lib/python3.7/site-packages (from scopen) (1.3.3)
Requirement already satisfied: scipy in ./.conda/envs/scopen_env/lib/python3.7/site-packages (from scopen) (1.7.1)
Requirement already satisfied: tables in ./.conda/envs/scopen_env/lib/python3.7/site-packages (from scopen) (3.6.1)
Requirement already satisfied: matplotlib in ./.conda/envs/scopen_env/lib/python3.7/site-packages (from scopen) (3.4.3)
Requirement already satisfied: scikit-learn in ./.conda/envs/scopen_env/lib/python3.7/site-packages (from scopen) (1.0)
Collecting kneed
  Using cached kneed-0.7.0-py2.py3-none-any.whl (9.4 kB)
Requirement already satisfied: cached-property in ./.conda/envs/scopen_env/lib/python3.7/site-packages (from h5py->scopen) (1.5.2)
Requirement already satisfied: pillow>=6.2.0 in ./.conda/envs/scopen_env/lib/python3.7/site-packages (from matplotlib->scopen) (8.3.2)
Requirement already satisfied: python-dateutil>=2.7 in ./.conda/envs/scopen_env/lib/python3.7/site-packages (from matplotlib->scopen) (2.8.2)
Requirement already satisfied: kiwisolver>=1.0.1 in ./.conda/envs/scopen_env/lib/python3.7/site-packages (from matplotlib->scopen) (1.3.2)
Requirement already satisfied: cycler>=0.10 in ./.conda/envs/scopen_env/lib/python3.7/site-packages (from matplotlib->scopen) (0.10.0)
Requirement already satisfied: pyparsing>=2.2.1 in ./.conda/envs/scopen_env/lib/python3.7/site-packages (from matplotlib->scopen) (2.4.7)
Requirement already satisfied: pytz>=2017.3 in ./.conda/envs/scopen_env/lib/python3.7/site-packages (from pandas->scopen) (2021.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in ./.conda/envs/scopen_env/lib/python3.7/site-packages (from scikit-learn->scopen) (3.0.0)
Requirement already satisfied: joblib>=0.11 in ./.conda/envs/scopen_env/lib/python3.7/site-packages (from scikit-learn->scopen) (1.1.0)
Requirement already satisfied: numexpr>=2.6.2 in ./.conda/envs/scopen_env/lib/python3.7/site-packages (from tables->scopen) (2.7.3)
Building wheels for collected packages: scopen
  Building wheel for scopen (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /PHShome/mt1036/.conda/envs/scopen_env/bin/python3.7 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1sijzu8m/scopen_9959595dd054491e888c848128e39679/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1sijzu8m/scopen_9959595dd054491e888c848128e39679/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-di0qgnto
       cwd: /tmp/pip-install-1sijzu8m/scopen_9959595dd054491e888c848128e39679/
  Complete output (14 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/scopen
  copying scopen/MF.py -> build/lib.linux-x86_64-3.7/scopen
  copying scopen/Main.py -> build/lib.linux-x86_64-3.7/scopen
  copying scopen/Utils.py -> build/lib.linux-x86_64-3.7/scopen
  copying scopen/__init__.py -> build/lib.linux-x86_64-3.7/scopen
  copying scopen/__version__.py -> build/lib.linux-x86_64-3.7/scopen
  running build_ext
  cythoning ./scopen/cdnmf_fast.pyx to ./scopen/cdnmf_fast.c
  error: /tmp/pip-install-1sijzu8m/scopen_9959595dd054491e888c848128e39679/scopen/cdnmf_fast.pyx
  ----------------------------------------
  ERROR: Failed building wheel for scopen
  Running setup.py clean for scopen
Failed to build scopen
Installing collected packages: kneed, scopen
    Running setup.py install for scopen ... error
    ERROR: Command errored out with exit status 1:
     command: /PHShome/mt1036/.conda/envs/scopen_env/bin/python3.7 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1sijzu8m/scopen_9959595dd054491e888c848128e39679/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1sijzu8m/scopen_9959595dd054491e888c848128e39679/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-rntjthxv/install-record.txt --single-version-externally-managed --compile --install-headers /PHShome/mt1036/.conda/envs/scopen_env/include/python3.7m/scopen
         cwd: /tmp/pip-install-1sijzu8m/scopen_9959595dd054491e888c848128e39679/
    Complete output (14 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/scopen
    copying scopen/MF.py -> build/lib.linux-x86_64-3.7/scopen
    copying scopen/Main.py -> build/lib.linux-x86_64-3.7/scopen
    copying scopen/Utils.py -> build/lib.linux-x86_64-3.7/scopen
    copying scopen/__init__.py -> build/lib.linux-x86_64-3.7/scopen
    copying scopen/__version__.py -> build/lib.linux-x86_64-3.7/scopen
    running build_ext
    cythoning ./scopen/cdnmf_fast.pyx to ./scopen/cdnmf_fast.c
    error: /tmp/pip-install-1sijzu8m/scopen_9959595dd054491e888c848128e39679/scopen/cdnmf_fast.pyx
    ----------------------------------------
ERROR: Command errored out with exit status 1: /PHShome/mt1036/.conda/envs/scopen_env/bin/python3.7 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1sijzu8m/scopen_9959595dd054491e888c848128e39679/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1sijzu8m/scopen_9959595dd054491e888c848128e39679/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-rntjthxv/install-record.txt --single-version-externally-managed --compile --install-headers /PHShome/mt1036/.conda/envs/scopen_env/include/python3.7m/scopen Check the logs for full command output.

**Comment by lzj1769** [comment]
Hi,

I am still trying to figure out what the problem is.
Meanwhile, you can try to install it from the source.

```
git clone git@github.com:CostaLab/scopen.git
cd scopen
pip install ./
```
In my case, I could reproduce the error, and here is what I did:
```
conda create -n scopen python=3.8
pip install scopen
```
It works pretty well.


Best,
Li

**Comment by MayaTalukdar** [comment]
Thank you very much, Li! This seems to work!

**Comment by rvinas** [comment]
Encountering the same error

**Comment by lzj1769** [comment]
@rvinas 

Can you provide your python version? also which system are you using?

**Comment by rvinas** [comment]
I'm using Python 3.8.5 on a Ubuntu machine (16.04)

**Comment by lzj1769** [comment]
Hi,

Can you try to install scopen from source?

```
git clone git@github.com:CostaLab/scopen.git
cd scopen
pip install ./
```

I tested it with the Conda environment of python3.8, but couldn't reproduce the error.

best,
Li

**Comment by lzj1769** [comment]
Closed with no further comments.

**Comment by alexlenail** [comment]
I also had this installation issue, and also solved it by downloading from github
